# Note! Make sure to change all occurences of "test" and the branch when copying this workflow.
#
# The following secrets are used in the workflow:
#
# ${{ secrets.GCP_PROJECT_ID }}
# ${{ secrets.GCP_REGION }}
# ${{ secrets.GCP_SERVICE_PREFIX }}
# ${{ secrets.GCP_CREDENTIALS }}
# ${{ secrets.GCP_SERVICE_ACCOUNT }}

env:
  DEPLOYMENT: test

name: Cloud Run Deploy - test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Authenticate Cloud SDK
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      - name: Build and push container
        run: |-
          docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_PREFIX }}-${{ env.DEPLOYMENT }}:${{ github.sha }} .
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_PREFIX }}-${{ env.DEPLOYMENT }}:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ secrets.GCP_SERVICE_PREFIX }}-${{ env.DEPLOYMENT }} \
            --region ${{ secrets.GCP_REGION }} \
            --image eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_PREFIX }}-${{ env.DEPLOYMENT }}:${{ github.sha }} \
            --platform "managed" \
            --quiet \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
            --port 80
